### ISSUE TITLE
RuntimeError: Invalid voice

### ISSUE THREAD

**Issue by CalculusAce** [Nanahuse/VoicepeakWrapper#1]
I am seeing an error related to the get_narrator_list function. For the majority of the voices I have installed, I cannot successfully retrieve the emotions that correspond to the voice. I am on VOICEPEAK 1.2.7 / Windows 10.

I made some adjustments to the library to see what was happening, and I found that the names of the narrators seem to be returning as separate items in the tuple that is returned from the get_narrator_list function. The tuple I get back looks as follows:

('Frimomen', 'Koharu', 'Rikka', 'Japanese', 'Female', 'Child', 'Japanese', 'Male', '3', 'Japanese', 'Male', '2', 'Japanese', 'Male', '1', 'Japanese', 'Female', '3', 'Japanese', 'Female', '2', 'Japanese', 'Female', '1')

I should note that I have additional voices installed beyond the original voices that come with VOICEPEAK, so perhaps that has something to do with the issue. Interestingly, I can retrieve emotions and use all of the library's features (writing files, etc) with "Frimomen" only. That voice is the only 1 in the tuple above that is not separated into multiple items as well. I have tried all combinations of the "Koharu Rikka" ("Koharu", "Rikka", "KoharuRikka", "Koharu_Rikka", etc) as an input argument to the get_emotion_list function, but I have not been able to get any emotions returned from VOICEPEAK for that voice.

Any input / help on this would be appreciated. Thank you for making this wrapper, it is very useful to have.

返事は日本語でも大丈夫です

**Comment by CalculusAce** [comment]
I managed to fix the issue. It appears that the --list-narrator command is returning a line separated string of names. Since I am on Windows, the split method isn't splitting the lines correctly. To make the code platform agnostic, the get_narrator_name_list method needs to be changed to use splitlines as follows:

```python
async def get_narrator_name_list(self) -> tuple[str]:
    """
    使用可能なナレーターを取得します。

    Returns:
        tuple[str]: ナレーターの名前一覧
    """
    return tuple(tmp for tmp in (await self.__async_run("--list-narrator")).splitlines())
```

Additionally, since the majority of the narrator names are composed of multiple words ("Japanese Male 1", "Koharu Rikka", etc), anywhere a narrator name is used as part of a command, it needs to be surrounded by quotes as follows:

```python
async def get_emotion_list(self, name: str) -> tuple[str]:
    """
    ナレーターの感情名一覧を取得する。

    Args:
        name (str): ナレーターの名前

    Returns:
        tuple[str]: ナレーターの感情名一覧
    """
    return tuple(tmp for tmp in (await self.__async_run(f"--list-emotion \"{name}\"")).split())
```

```python
# __make_say_command method snippet
match narrator:
    case Narrator():
        command.append(f"-n \"{narrator.name}\"")
    case str():
        command.append(f"-n \"{narrator}\"")
    case None:
        pass
```

These adjustments address all the issues I was having using the library on Windows. If you'd like, I can open a PR to get these fixes merged. While I suspect it'll still work, I don't have VOICEPEAK installed on any unix-based OS's at the moment, so that'll have to be tested to verify the changes work there as well.

**Comment by Nanahuse** [comment]
@CalculusAce 
thank you for your detailed issue report.
Could you please send PR about it?

I agree your changes. 
`--line-narrator` command return line separated strings.
I didnt test multiple narrators case...

`--list-emotions` command also return  line separated strings.
it need same change.
and enclosing name in "" is very good point. (i would never realize its importance without your report. Because it work with or without ""  in Jpanese enviroment.)  
but how about enclosing str in single quote instead of enclosing str in double quote with `\"`.

ex.
```
match narrator:
    case Narrator():
        command.append(f'-n "{narrator.name}"')
    case str():
        command.append(f'-n "{narrator}"')
    case None:
        pass
```
