### ISSUE TITLE
Feature Request - Add Support to Pipe VOICEPEAK WAV File Output to STDOUT / Buffer

### ISSUE THREAD

**Issue by CalculusAce** [Nanahuse/VoicepeakWrapper#4]
I am not sure offhand if this can be done with VOICEPEAK via some modifications to the commands / python code, but I feel there are some benefits to being able to do this, if it is possible anyway.

1. If the output WAV file can be piped, you can use ffmpeg (accepts piped input / STDIN) within python to convert the audio directly to a more space efficient codec (mp3, ogg, etc). Currently WAV files have to be written to disk before using ffmpeg to do the conversion, which takes a lot more time when using the wrapper to produce audio in bulk compared to if it were possible to handle the conversion prior to any files being written to disk.
2. If the output WAV file can be piped, additional audio libraries (pydub, etc) could be used to further manipulate the audio before writing it to disk. Pydub also supports direct playback of audio from within python, which would make recalibrating VOICEPEAK narration settings easier to do from within your IDE without having to write a file to check if you're satisfied with the audio output.

I am happy to look into this as well, but I wanted to see if you could link any documentation you have found on using VOICEPEAK with command line commands (I am unaware of any 1st party docs on that provided by AHS) / if you have any thoughts on this potential feature?

**Comment by Nanahuse** [comment]
This feature sounds very useful. 
But I can't think of how to implement it. I guess current cli cannot pipe WAV data directly without save.

Currently, I don't have any plans to work on new feature beyond wrapping cli commands.
However, I will welcom your PR.

I have not find the official reference of cli yet. It's possible that the cli  is still in alpha.
But we can get a bit command doc about cli.
```.\voicepeak.exe --help```

I will reopen this issue if you have any ideas or the intention to work on it.
